### ISSUE TITLE
cannot import name EngListener

### ISSUE THREAD

**Issue by wheelq** [DefectDojo/Burp-Plugin#18]
I did download both py files
I did follow the instructions (apart from the previous step).
And here is the error:

```
Traceback (most recent call last):
  File "/Users/test/DefectDojoPlugin.py", line 43, in <module>
    from utils import EngListener, ProdListener, TestListener, ProdMouseListener
ImportError: cannot import name EngListener

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.importFromAs(imp.java:1632)
	at org.python.core.imp.importFrom(imp.java:1595)
	at org.python.pycode._pyx4.f$0(/Users/test/DefectDojoPlugin.py:659)
	at org.python.pycode._pyx4.call_function(/Users/test/DefectDojoPlugin.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:287)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at burp.epl.<init>(Unknown Source)
	at burp.h0v.a(Unknown Source)
	at burp.efu.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

```

**Comment by adracea** [comment]
I know this might be old but did you manage to fix this ? Looks to me like utils.py was not in the same folder as the DefectDojoPlugin.py .

**Comment by twright-0x1** [comment]
For anyone who wanders this way...  The instructions aren't clear on how the DefectDojoPlugin should be installed within BurpSuite Pro.  Here's what got things working for me:

1. Decide where on your system you would like to store Python files for use in Burp.  Let's call this 'location_x'

2. Snarf down the utils.py and DefectDojoPlugin.py files from this repository and store them in location_x

3. Within Burp, select the Extensions tab, then the Options sub-tab, and setup Jython (if you need to, download the latest Jython JAR, store that in a reasonable place, and point Burp at it).  In particular, add the path to location_x in the text box under "Folder for loading modules (optional)"

4. Switch over to the Installed sub-tab (still under the Extensions tab)

5. Click the Add button.  In the resulting dialog, under Extension Details, select Python for the Extension type and click the "Select file..." 

6. You should now see a new dialog that shows you the contents of location_x.  Simply select DefectDojoPlugin.py and click Open

7. Click Next and you should be good to go

**Comment by ghost** [comment]
This unfortunately did not fix the issue for me. I am still seeing the following error: 
<img width="419" alt="image" src="https://user-images.githubusercontent.com/47400337/216136641-93caa544-ce21-4358-9822-a451c4517bb3.png">

**Comment by adracea** [comment]
Hello, if I remember correctly this requires the `jython.jar` file to be added. I'm not currently sure if this is still supported, I will check tomorrow and try to update if possible.

Edit: https://portswigger.net/burp/documentation/desktop/extensions/installing-extensions#installing-jython-or-jruby seems relevant.

https://www.jython.org/download.html is the relevant download link. You'd be looking for the standalone `.jar` file.

**Comment by mtesauro** [comment]
Archiving this repo - The Burp plug-in depends on jython, which is now outdated and it has been a year since a formal release.
