### ISSUE TITLE
Issues with Burp v2020.9.2 and DD 1.9

### ISSUE THREAD

**Issue by dsever** [DefectDojo/Burp-Plugin#22]
Durig the demo I run into the problem,  that reflects as tests are created but, if I click on test it breaks down DD. 

Error: 'NoneType' object has no attribute 'split'
Error: 'NoneType' object has no attribute 'split'
Error: 'NoneType' object has no attribute 'split'

and 

```
Unhandled exception in thread started by <bound method BurpExtender.doGetProducts of org.python.proxies.__main__$BurpExtender$13@646b9cc0>
Unhandled exception in thread started by <bound method BurpExtender.doGetProducts of org.python.proxies.__main__$BurpExtender$13@646b9cc0>
Unhandled exception in thread started by <bound method BurpExtender.doGetProducts of org.python.proxies.__main__$BurpExtender$13@646b9cc0>
Unhandled exception in thread started by <bound method BurpExtender.doGetProducts of org.python.proxies.__main__$BurpExtender$13@646b9cc0>
Traceback (most recent call last):
  File "/home/dsever/Pan-Net/test-projects2020/Burp-Plugin/DefectDojoPlugin.py", line 287, in doGetProducts
    test = DefectDojoResponse(message="Done",
  File "/home/dsever/Pan-Net/test-projects2020/Burp-Plugin/DefectDojoPlugin.py", line 668, in __init__
    self.data = json.loads(data)
  File "/opt/jyton/jython-standalone-2.7.2.jar/Lib/json/__init__.py", line 338, in loads
  File "/opt/jyton/jython-standalone-2.7.2.jar/Lib/json/decoder.py", line 365, in decode
  File "/opt/jyton/jython-standalone-2.7.2.jar/Lib/json/decoder.py", line 383, in raw_decode
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/home/dsever/Pan-Net/test-projects2020/Burp-Plugin/DefectDojoPlugin.py", line 287, in doGetProducts
    test = DefectDojoResponse(message="Done",
  File "/home/dsever/Pan-Net/test-projects2020/Burp-Plugin/DefectDojoPlugin.py", line 668, in __init__
    self.data = json.loads(data)
  File "/opt/jyton/jython-standalone-2.7.2.jar/Lib/json/__init__.py", line 338, in loads
  File "/opt/jyton/jython-standalone-2.7.2.jar/Lib/json/decoder.py", line 365, in decode
  File "/opt/jyton/jython-standalone-2.7.2.jar/Lib/json/decoder.py", line 383, in raw_decode
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/home/dsever/Pan-Net/test-projects2020/Burp-Plugin/DefectDojoPlugin.py", line 287, in doGetProducts
    test = DefectDojoResponse(message="Done",
  File "/home/dsever/Pan-Net/test-projects2020/Burp-Plugin/DefectDojoPlugin.py", line 668, in __init__
    self.data = json.loads(data)
  File "/opt/jyton/jython-standalone-2.7.2.jar/Lib/json/__init__.py", line 338, in loads
  File "/opt/jyton/jython-standalone-2.7.2.jar/Lib/json/decoder.py", line 365, in decode
  File "/opt/jyton/jython-standalone-2.7.2.jar/Lib/json/decoder.py", line 383, in raw_decode
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/home/dsever/Pan-Net/test-projects2020/Burp-Plugin/DefectDojoPlugin.py", line 287, in doGetProducts
    test = DefectDojoResponse(message="Done",
  File "/home/dsever/Pan-Net/test-projects2020/Burp-Plugin/DefectDojoPlugin.py", line 668, in __init__
    self.data = json.loads(data)
  File "/opt/jyton/jython-standalone-2.7.2.jar/Lib/json/__init__.py", line 338, in loads
  File "/opt/jyton/jython-standalone-2.7.2.jar/Lib/json/decoder.py", line 365, in decode
  File "/opt/jyton/jython-standalone-2.7.2.jar/Lib/json/decoder.py", line 383, in raw_decode
ValueError: No JSON object could be decoded
```
In Burp I have logs.

As far as i remember there is an issue fro 1.7 with API, while apiv2 was fixed, apiv1 did not

**Comment by adracea** [comment]
I'll get back to working on this this weekend.

**Comment by adracea** [comment]
The issue is with a missing import in defect dojo. I've raised a PR to fix it there.

**Comment by dsever** [comment]
@adracea APIv1 is not under maintenance anymore

**Comment by adracea** [comment]
I'm working on adding the support necessary for API v2. In the meantime, I'm pretty sure the PR for fixing the missing import will be added to the next release of DefectDojo.
